update changes.
oshi/oshi pull request #2473
Opened 2023-10-09 17:43 UTC by Palak4620

2023-10-09 22:49 UTC, dbwiddis requested changes

2023-10-09 22:49 UTC, dbwiddis commented on oshi-core/src/main/java/oshi/annotation/concurrent/SuppressForbidden.java
1. Just put this in `oshi.annotation`, not the concurrent subpackage.
2. You'll need to update the import statements where this is used in `oshi.demo`.

2023-10-09 22:49 UTC, dbwiddis commented on pom.xml
> +        </plugin>
This is the wrong plugin to add.  Go to the `forbiddenapis` plugin here:
https://github.com/oshi/oshi/blob/2a37177fe9c9c5c96f6711b62d7b8c97814f0d09/pom.xml#L746-L770

You'll be adding the `<signatureFiles>` section inside configuration.  See sample POM entry [here](https://github.com/policeman-tools/forbidden-apis/wiki/MavenUsage#maven-usage-instructions).  Format of that file (you can put it in the `config` directory under root) is [here](https://github.com/policeman-tools/forbidden-apis/wiki/SignaturesSyntax#syntax-of-forbidden-signatures).

2023-10-10 02:34 UTC, Palak4620 commented on oshi-core/src/main/java/oshi/annotation/concurrent/SuppressForbidden.java
okay, I will do that.

2023-10-10 15:14 UTC, dbwiddis commented
Superceced by #2474

2023-10-10 15:14 UTC, closed without merging